# +=
weather = int(20)
print("The sun degree is, {0}".format(weather))
weather += int(input('+= : '))
print("The += of sun degree is, {0}".format(weather))
weather = weather + int(input('= weather +  : '))
print("The New sun degree is, {0}".format(weather))
weather -= int(input('-= : '))
print("The += of sun degree is, {0}".format(weather))
weather = weather - int(input('= weather -  : '))
print("The New sun degree is, {0}".format(weather))
weather *= int(input('*= : '))
print("The *= of sun degree is, {0}".format(weather))
weather = weather + int(input('= weather *  : '))
print("The New sun degree is, {0}".format(weather))
weather /= int(input('/= : '))
print("The /= of sun degree is, {0}".format(weather))
weather = weather + int(input('= weather /  : '))
print("The New sun degree is, {0}".format(weather))
weather **= int(input('**= : '))
print("The **= of sun degree is, {0}".format(weather))
weather = weather + int(input('= weather **  : '))
print("The New sun degree is, {0}".format(weather))